before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/inv
    binary: inv
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^Docs:"
      - "^test:"
      - "^Test:"
      - "^ci:"
      - "^CI:"
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - repository:
      owner: dev01d
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/dev01d/inv
    description: A formatted investigation tool
    skip_upload: auto
    test: |
      system "#{bin}/inv --version"
nfpms:
  - id: packages
    maintainer: Jason Behnke <jason@jasonbehnke.io>
    homepage: https://github.com/dev01d/inv
    description: A formatted investigation tool
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/dev01d/
